// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.1
//   protoc               v5.28.2
// source: proto/payment_processor.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payment_processor";

export interface Empty {
}

export interface Transactions {
  Transactions: GetTransactionDTO[];
}

export interface GetTransactionDTO {
  id: string;
  transactionOriginId: string;
  network: string;
  merchantName: string;
  authTransactionAmount: string;
  clearingTransactionAmount?: string | undefined;
  transactionCurrency: string;
  authTransactionTimestamp: string;
  clearingtransactionTimestamp?: string | undefined;
}

export interface TransactionDTO {
  id: string;
  transactionOriginId: string;
  network: string;
  transactionType: string;
  transactionProcessor: string;
  merchantName: string;
  transactionAmount: string;
  transactionCurrency: string;
  transactionTimestamp: string;
}

export const PAYMENT_PROCESSOR_PACKAGE_NAME = "payment_processor";

export interface PaymentProcessorServiceClient {
  getTransactions(request: Empty): Observable<Transactions>;

  processTransaction(request: TransactionDTO): Observable<Empty>;
}

export interface PaymentProcessorServiceController {
  getTransactions(request: Empty): Promise<Transactions> | Observable<Transactions> | Transactions;

  processTransaction(request: TransactionDTO): Promise<Empty> | Observable<Empty> | Empty;
}

export function PaymentProcessorServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getTransactions", "processTransaction"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentProcessorService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentProcessorService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_PROCESSOR_SERVICE_NAME = "PaymentProcessorService";
